# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 749)
        MainWindow.setMinimumSize(QtCore.QSize(940, 560))
        self.styleSheet = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.styleSheet.setFont(font)
        self.styleSheet.setAcceptDrops(True)
        self.styleSheet.setStyleSheet("QWidget{\n"
"    color: rgb(221, 221, 221);\n"
"    font: 87 10pt \"Roboto Black\";\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(33, 37, 43, 180);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(255, 121, 198);\n"
"    text-align: left;\n"
"    padding-left: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Bg App */\n"
"#bgApp {    \n"
"    background-color: #007ACC;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Left Menu */\n"
"#leftMenuBg {    \n"
"    background-color:#007ACC;\n"
"}\n"
"#topLogo {\n"
"    background-color: #007ACC;\n"
"    image: url(:/images/images/images/Small-logo.ico);\n"
"    background-position: centered;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"#titleLeftApp { font: 63 12pt \"Segoe UI Semibold\"; }\n"
"#titleLeftDescription { font: 8pt \"Segoe UI\"; color: #345CBF; }\n"
"\n"
"/* MENUS */\n"
"#topMenu .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#topMenu .QPushButton:hover {\n"
"    background-color: #0061B0;\n"
"}\n"
"#topMenu .QPushButton:pressed {    \n"
"    background-color: #0061B0;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#bottomMenu .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#bottomMenu .QPushButton:hover {\n"
"    background-color: #0061B0;\n"
"}\n"
"#bottomMenu .QPushButton:pressed {    \n"
"    background-color: #0061B0;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#leftMenuFrame{\n"
"    border-top: 3px solid #007AC;\n"
"}\n"
"\n"
"/* Toggle Button */\n"
"#toggleButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    text-align: left;\n"
"    color: rgb(113, 126, 149);\n"
"}\n"
"\n"
"#rightButtons .QPushButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    text-align: left;\n"
"    color: rgb(113, 126, 149);\n"
"}\n"
"\n"
"/* Title Menu */\n"
"#titleRightInfo { padding-left: 10px; }\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Extra Tab */\n"
"#extraLeftBox {    \n"
"    background-color: rgb(44, 49, 58);\n"
"}\n"
"#extraTopBg{    \n"
"    background-color: #345CBF\n"
"}\n"
"\n"
"/* Icon */\n"
"#extraIcon {\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-image: url(:/icons/images/icons/icon_settings.png);\n"
"}\n"
"\n"
"\n"
"\n"
"/* Extra Top Menus */\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Content App */\n"
"#contentTopBg{    \n"
"    background-color: #F5F5F5;\n"
"}\n"
"#contentBottom{\n"
"    border-top: 3px solid #F5F5F5;\n"
"}\n"
"\n"
"/* Top Buttons */\n"
"\n"
"\n"
"/* Theme Settings */\n"
"#extraRightBox { background-color:#007ACC; }\n"
"#themeSettingsTopDetail { background-color: #345CBF; }\n"
"\n"
"/* Bottom Bar */\n"
"\n"
"\n"
"/* CONTENT SETTINGS */\n"
"/* MENUS */\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"QTableWidget {    \n"
"    background-color: #444;\n"
"    padding: 5px;\n"
"    border-radius: 8px;\n"
"    gridline-color: #555;\n"
"    color: #FFF;\n"
"}\n"
"QTableWidget::item {\n"
"    border-color: none;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: #555;\n"
"    border-bottom: 1px solid #555;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #00ABE8;\n"
"    color: #FFF;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #345CBF;\n"
"    max-width: 30px;\n"
"    border: 1px solid #555;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid #555;\n"
"    border-right: 1px solid #555;\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: #345CBF;\n"
"}\n"
"QTableWidget QTableCornerButton::section {\n"
"    border: none;\n"
"    background-color: #333;\n"
"    padding: 3px;\n"
"    border-top-left-radius: 8px;\n"
"}\n"
"QHeaderView::section:horizontal {\n"
"    border: none;\n"
"    background-color: #345CBF ;\n"
"    padding: 3px;\n"
"}\n"
"QHeaderView::section:vertical {\n"
"    border: none;\n"
"    background-color: #444;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border-bottom: 1px solid #555;\n"
"    margin-bottom: 1px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    background: #FFF;\n"
"    height: 8px;\n"
"    margin: 0px 16px 0 16px;\n"
"    border: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: #FFF;\n"
"    width: 8px;\n"
"    margin: 16px 0 16px 0;\n"
"    border: none;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #3333;\n"
"    min-width: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #3333;\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"LineEdit */\n"
"QLineEdit {\n"
"background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QPlainTextEdit  QScrollBar:vertical {\n"
"    width: 8px;\n"
" }\n"
"QPlainTextEdit  QScrollBar:horizontal {\n"
"    height: 8px;\n"
" }\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #345CBF;\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: #345CBF;\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CheckBox */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: #345CBF;\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 5px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: #345CBF;\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CommandLinkButton */\n"
"QCommandLinkButton {    \n"
"    color: rgb(255, 121, 198);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 170, 255);\n"
"}\n"
"QCommandLinkButton:hover {    \n"
"    color: rgb(255, 170, 255);\n"
"    background-color: rgb(44, 49, 60);\n"
"}\n"
"QCommandLinkButton:pressed {    \n"
"    color: #345CBF;\n"
"    background-color: rgb(52, 58, 71);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Button */\n"
"\n"
"\n"
"")
        self.styleSheet.setObjectName("styleSheet")
        self.appMargins = QtWidgets.QVBoxLayout(self.styleSheet)
        self.appMargins.setContentsMargins(0, 0, 0, 0)
        self.appMargins.setSpacing(0)
        self.appMargins.setObjectName("appMargins")
        self.bgApp = QtWidgets.QFrame(self.styleSheet)
        self.bgApp.setStyleSheet("")
        self.bgApp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bgApp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bgApp.setObjectName("bgApp")
        self.appLayout = QtWidgets.QHBoxLayout(self.bgApp)
        self.appLayout.setContentsMargins(0, 0, 0, 0)
        self.appLayout.setSpacing(0)
        self.appLayout.setObjectName("appLayout")
        self.leftMenuBg = QtWidgets.QFrame(self.bgApp)
        self.leftMenuBg.setMinimumSize(QtCore.QSize(60, 0))
        self.leftMenuBg.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leftMenuBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuBg.setObjectName("leftMenuBg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftMenuBg)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.leftMenuFrame = QtWidgets.QFrame(self.leftMenuBg)
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalMenuLayout = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalMenuLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalMenuLayout.setSpacing(0)
        self.verticalMenuLayout.setObjectName("verticalMenuLayout")
        self.topMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.topMenu.setStyleSheet("font: 75 14pt \"Roboto Condensed\";")
        self.topMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topMenu.setObjectName("topMenu")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.topMenu)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lblLogo = QtWidgets.QLabel(self.topMenu)
        self.lblLogo.setMinimumSize(QtCore.QSize(0, 0))
        self.lblLogo.setMaximumSize(QtCore.QSize(16777215, 190))
        self.lblLogo.setStyleSheet("")
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap(":/images/images/images/logo.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.verticalLayout_8.addWidget(self.lblLogo)
        self.topLogo = QtWidgets.QFrame(self.topMenu)
        self.topLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLogo.setObjectName("topLogo")
        self.verticalLayout_8.addWidget(self.topLogo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.btnProjects = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnProjects.sizePolicy().hasHeightForWidth())
        self.btnProjects.setSizePolicy(sizePolicy)
        self.btnProjects.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnProjects.setFont(font)
        self.btnProjects.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnProjects.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnProjects.setStyleSheet("background-image: url(:/icons/images/icons/icons8-graph-20.png);")
        self.btnProjects.setObjectName("btnProjects")
        self.verticalLayout_8.addWidget(self.btnProjects)
        self.btnCriteria = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCriteria.sizePolicy().hasHeightForWidth())
        self.btnCriteria.setSizePolicy(sizePolicy)
        self.btnCriteria.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnCriteria.setFont(font)
        self.btnCriteria.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCriteria.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnCriteria.setStyleSheet("background-image: url(:/icons/images/icons/icons8-menu-settings-20.png);")
        self.btnCriteria.setObjectName("btnCriteria")
        self.verticalLayout_8.addWidget(self.btnCriteria)
        self.btnSensorList = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSensorList.sizePolicy().hasHeightForWidth())
        self.btnSensorList.setSizePolicy(sizePolicy)
        self.btnSensorList.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnSensorList.setFont(font)
        self.btnSensorList.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSensorList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnSensorList.setStyleSheet("background-image: url(:/icons/images/icons/icons8-apk-20.png);")
        self.btnSensorList.setObjectName("btnSensorList")
        self.verticalLayout_8.addWidget(self.btnSensorList)
        self.btnTestList = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTestList.sizePolicy().hasHeightForWidth())
        self.btnTestList.setSizePolicy(sizePolicy)
        self.btnTestList.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnTestList.setFont(font)
        self.btnTestList.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnTestList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnTestList.setStyleSheet("background-image: url(:/icons/images/icons/icons8-update-20.png);")
        self.btnTestList.setObjectName("btnTestList")
        self.verticalLayout_8.addWidget(self.btnTestList)
        self.btnPlanning = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPlanning.sizePolicy().hasHeightForWidth())
        self.btnPlanning.setSizePolicy(sizePolicy)
        self.btnPlanning.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnPlanning.setFont(font)
        self.btnPlanning.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPlanning.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnPlanning.setStyleSheet("background-image: url(:/icons/images/icons/icon_settings.png);")
        self.btnPlanning.setObjectName("btnPlanning")
        self.verticalLayout_8.addWidget(self.btnPlanning)
        self.btnProjects.raise_()
        self.btnCriteria.raise_()
        self.btnTestList.raise_()
        self.btnPlanning.raise_()
        self.btnSensorList.raise_()
        self.lblLogo.raise_()
        self.topLogo.raise_()
        self.verticalMenuLayout.addWidget(self.topMenu, 0, QtCore.Qt.AlignTop)
        self.bottomMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.bottomMenu.setStyleSheet("font: 75 11pt \"Roboto Condensed\";")
        self.bottomMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomMenu.setObjectName("bottomMenu")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.bottomMenu)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btnInfo = QtWidgets.QPushButton(self.bottomMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnInfo.sizePolicy().hasHeightForWidth())
        self.btnInfo.setSizePolicy(sizePolicy)
        self.btnInfo.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnInfo.setFont(font)
        self.btnInfo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInfo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnInfo.setStyleSheet("background-image: url(:/icons/images/icons/cil-options.png);")
        self.btnInfo.setObjectName("btnInfo")
        self.verticalLayout_9.addWidget(self.btnInfo)
        self.verticalMenuLayout.addWidget(self.bottomMenu, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_3.addWidget(self.leftMenuFrame)
        self.appLayout.addWidget(self.leftMenuBg)
        self.contentBox = QtWidgets.QFrame(self.bgApp)
        self.contentBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentTopBg = QtWidgets.QFrame(self.contentBox)
        self.contentTopBg.setMinimumSize(QtCore.QSize(0, 40))
        self.contentTopBg.setMaximumSize(QtCore.QSize(16777215, 40))
        self.contentTopBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTopBg.setObjectName("contentTopBg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBg)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBox = QtWidgets.QFrame(self.contentTopBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBox.sizePolicy().hasHeightForWidth())
        self.leftBox.setSizePolicy(sizePolicy)
        self.leftBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBox.setObjectName("leftBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.leftBox)
        self.horizontalLayout_3.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toggleButton = QtWidgets.QPushButton(self.leftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleButton.sizePolicy().hasHeightForWidth())
        self.toggleButton.setSizePolicy(sizePolicy)
        self.toggleButton.setMinimumSize(QtCore.QSize(0, 0))
        self.toggleButton.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.toggleButton.setFont(font)
        self.toggleButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toggleButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toggleButton.setStyleSheet("")
        self.toggleButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-menu-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleButton.setIcon(icon)
        self.toggleButton.setIconSize(QtCore.QSize(30, 30))
        self.toggleButton.setObjectName("toggleButton")
        self.horizontalLayout_3.addWidget(self.toggleButton, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.leftBox)
        self.rightButtons = QtWidgets.QFrame(self.contentTopBg)
        self.rightButtons.setMinimumSize(QtCore.QSize(0, 28))
        self.rightButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightButtons.setObjectName("rightButtons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rightButtons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimizeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeAppBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-horizontal-line-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeAppBtn.setIcon(icon1)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_2.addWidget(self.minimizeAppBtn)
        self.maximizeRestoreAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.maximizeRestoreAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.maximizeRestoreAppBtn.setFont(font)
        self.maximizeRestoreAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maximizeRestoreAppBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-rectangle-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizeRestoreAppBtn.setIcon(icon2)
        self.maximizeRestoreAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.maximizeRestoreAppBtn.setObjectName("maximizeRestoreAppBtn")
        self.horizontalLayout_2.addWidget(self.maximizeRestoreAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeAppBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-close-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeAppBtn.setIcon(icon3)
        self.closeAppBtn.setIconSize(QtCore.QSize(25, 25))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_2.addWidget(self.closeAppBtn)
        self.horizontalLayout.addWidget(self.rightButtons, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.contentTopBg)
        self.contentBottom = QtWidgets.QFrame(self.contentBox)
        self.contentBottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBottom.setObjectName("contentBottom")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.contentBottom)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.content = QtWidgets.QFrame(self.contentBottom)
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pagesContainer = QtWidgets.QFrame(self.content)
        self.pagesContainer.setStyleSheet("#pagesContainer{\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLabel{\n"
"\n"
"    font: 87 10pt \"Roboto Black\";\n"
"\n"
"color:black;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border-radius: 5px;\n"
"    border: 1px solid gray;\n"
"    padding-left: 5px;\n"
"    selection-color: #fff;\n"
"    selection-background-color: #1159A8;\n"
"    font-family: Calibri;\n"
"color:black\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid gray;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid gray;\n"
"    background-color: #FAFAFC;\n"
"}\n"
"QComboBox{\n"
"    background-color: #1159A8;\n"
"    border-radius: 5px;\n"
"    border: 1px solid gray;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"color:black;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 1px solid gray;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/icons/images/icons/icons8-arrow-down-20.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color:  red;    \n"
"    background-color:#fff;\n"
"    padding: 10px;\n"
"    selection-background-color: #fff;\n"
"}\n"
"\n"
"")
        self.pagesContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pagesContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pagesContainer.setObjectName("pagesContainer")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.pagesContainer)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.stackedWidget = QtWidgets.QStackedWidget(self.pagesContainer)
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.projectPage = QtWidgets.QWidget()
        self.projectPage.setAcceptDrops(True)
        self.projectPage.setStyleSheet("QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    background-color: #007ACC;\n"
"    padding: 10px;\n"
"    color:#fff;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0061B0;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: #0061B0;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.projectPage.setObjectName("projectPage")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.projectPage)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame = QtWidgets.QFrame(self.projectPage)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setStyleSheet("font: 75 14pt \"Roboto Condensed\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.verticalLayout_21.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnZoekAfse = QtWidgets.QPushButton(self.frame_3)
        self.btnZoekAfse.setObjectName("btnZoekAfse")
        self.horizontalLayout_5.addWidget(self.btnZoekAfse)
        self.btnZoekMehi = QtWidgets.QPushButton(self.frame_3)
        self.btnZoekMehi.setObjectName("btnZoekMehi")
        self.horizontalLayout_5.addWidget(self.btnZoekMehi)
        self.btnZoekSUO = QtWidgets.QPushButton(self.frame_3)
        self.btnZoekSUO.setObjectName("btnZoekSUO")
        self.horizontalLayout_5.addWidget(self.btnZoekSUO)
        self.verticalLayout_21.addWidget(self.frame_3)
        self.horizontalLayout_6.addWidget(self.frame)
        self.stackedWidget.addWidget(self.projectPage)
        self.widgets = QtWidgets.QWidget()
        self.widgets.setStyleSheet("b")
        self.widgets.setObjectName("widgets")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgets)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget.addWidget(self.widgets)
        self.MenuCompilerPage = QtWidgets.QWidget()
        self.MenuCompilerPage.setObjectName("MenuCompilerPage")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.MenuCompilerPage)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.stackedWidget.addWidget(self.MenuCompilerPage)
        self.UpdateCheckPage = QtWidgets.QWidget()
        self.UpdateCheckPage.setObjectName("UpdateCheckPage")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.UpdateCheckPage)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.stackedWidget.addWidget(self.UpdateCheckPage)
        self.PairipPassPage = QtWidgets.QWidget()
        self.PairipPassPage.setObjectName("PairipPassPage")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.PairipPassPage)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label = QtWidgets.QLabel(self.PairipPassPage)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_32.addWidget(self.label)
        self.stackedWidget.addWidget(self.PairipPassPage)
        self.OffsetLeechPage = QtWidgets.QWidget()
        self.OffsetLeechPage.setObjectName("OffsetLeechPage")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.OffsetLeechPage)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_2 = QtWidgets.QLabel(self.OffsetLeechPage)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_33.addWidget(self.label_2)
        self.stackedWidget.addWidget(self.OffsetLeechPage)
        self.MultiToolPage = QtWidgets.QWidget()
        self.MultiToolPage.setObjectName("MultiToolPage")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.MultiToolPage)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_3 = QtWidgets.QLabel(self.MultiToolPage)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_34.addWidget(self.label_3)
        self.stackedWidget.addWidget(self.MultiToolPage)
        self.verticalLayout_15.addWidget(self.stackedWidget)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.pagesContainer)
        self.stackedWidget_2.setStyleSheet("background: transparent;")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.page_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_12.addWidget(self.label_4)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_5 = QtWidgets.QFrame(self.page_6)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_16.addWidget(self.label_6)
        self.verticalLayout_10.addWidget(self.frame_5)
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_6 = QtWidgets.QFrame(self.page_7)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_17.addWidget(self.label_7)
        self.verticalLayout_11.addWidget(self.frame_6)
        self.stackedWidget_2.addWidget(self.page_7)
        self.verticalLayout_15.addWidget(self.stackedWidget_2)
        self.bottomBar_2 = QtWidgets.QFrame(self.pagesContainer)
        self.bottomBar_2.setMinimumSize(QtCore.QSize(0, 22))
        self.bottomBar_2.setMaximumSize(QtCore.QSize(16777215, 22))
        self.bottomBar_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomBar_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomBar_2.setObjectName("bottomBar_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.bottomBar_2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.version_3 = QtWidgets.QLabel(self.bottomBar_2)
        self.version_3.setText("")
        self.version_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version_3.setObjectName("version_3")
        self.horizontalLayout_14.addWidget(self.version_3)
        self.frame_size_grip = QtWidgets.QFrame(self.bottomBar_2)
        self.frame_size_grip.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_14.addWidget(self.frame_size_grip)
        self.verticalLayout_15.addWidget(self.bottomBar_2)
        self.horizontalLayout_4.addWidget(self.pagesContainer)
        self.extraRightBox = QtWidgets.QFrame(self.content)
        self.extraRightBox.setMinimumSize(QtCore.QSize(0, 0))
        self.extraRightBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.extraRightBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraRightBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraRightBox.setObjectName("extraRightBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.extraRightBox)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.themeSettingsTopDetail = QtWidgets.QFrame(self.extraRightBox)
        self.themeSettingsTopDetail.setMaximumSize(QtCore.QSize(16777215, 3))
        self.themeSettingsTopDetail.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.themeSettingsTopDetail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.themeSettingsTopDetail.setObjectName("themeSettingsTopDetail")
        self.verticalLayout_7.addWidget(self.themeSettingsTopDetail)
        self.contentSettings = QtWidgets.QFrame(self.extraRightBox)
        self.contentSettings.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentSettings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentSettings.setObjectName("contentSettings")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.contentSettings)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.topMenus = QtWidgets.QFrame(self.contentSettings)
        self.topMenus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topMenus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topMenus.setObjectName("topMenus")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.topMenus)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.btn_message = QtWidgets.QPushButton(self.topMenus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_message.sizePolicy().hasHeightForWidth())
        self.btn_message.setSizePolicy(sizePolicy)
        self.btn_message.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.btn_message.setFont(font)
        self.btn_message.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_message.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_message.setStyleSheet("background-image: url(:/icons/images/icons/cil-envelope-open.png);")
        self.btn_message.setObjectName("btn_message")
        self.verticalLayout_14.addWidget(self.btn_message)
        self.btn_print = QtWidgets.QPushButton(self.topMenus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_print.sizePolicy().hasHeightForWidth())
        self.btn_print.setSizePolicy(sizePolicy)
        self.btn_print.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.btn_print.setFont(font)
        self.btn_print.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_print.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_print.setStyleSheet("background-image: url(:/icons/images/icons/cil-print.png);")
        self.btn_print.setObjectName("btn_print")
        self.verticalLayout_14.addWidget(self.btn_print)
        self.btn_logout = QtWidgets.QPushButton(self.topMenus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_logout.sizePolicy().hasHeightForWidth())
        self.btn_logout.setSizePolicy(sizePolicy)
        self.btn_logout.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.btn_logout.setFont(font)
        self.btn_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_logout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_logout.setStyleSheet("background-image: url(:/icons/images/icons/cil-account-logout.png);")
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout_14.addWidget(self.btn_logout)
        self.verticalLayout_13.addWidget(self.topMenus, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_7.addWidget(self.contentSettings)
        self.horizontalLayout_4.addWidget(self.extraRightBox)
        self.verticalLayout_6.addWidget(self.content)
        self.verticalLayout_2.addWidget(self.contentBottom)
        self.appLayout.addWidget(self.contentBox)
        self.appMargins.addWidget(self.bgApp)
        MainWindow.setCentralWidget(self.styleSheet)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnProjects.setText(_translate("MainWindow", "Zoeken"))
        self.btnCriteria.setText(_translate("MainWindow", "Berekenen"))
        self.btnSensorList.setText(_translate("MainWindow", "Documenten "))
        self.btnTestList.setText(_translate("MainWindow", "Testen"))
        self.btnPlanning.setText(_translate("MainWindow", "Instellingen"))
        self.btnInfo.setText(_translate("MainWindow", "SIDTEUA ∝ SIDKUEY"))
        self.minimizeAppBtn.setToolTip(_translate("MainWindow", "Minimize"))
        self.maximizeRestoreAppBtn.setToolTip(_translate("MainWindow", "Maximize"))
        self.closeAppBtn.setToolTip(_translate("MainWindow", "Close"))
        self.label_5.setText(_translate("MainWindow", "Zoekfunctie REG"))
        self.btnZoekAfse.setText(_translate("MainWindow", "Zoek Afseuiter"))
        self.btnZoekMehi.setText(_translate("MainWindow", "Zoek Mehingen"))
        self.btnZoekSUO.setText(_translate("MainWindow", "Zoek SUO"))
        self.label.setText(_translate("MainWindow", "Pairip Page Yet to be Implemented"))
        self.label_2.setText(_translate("MainWindow", "Offset Leech Page Yet to be Implemented"))
        self.label_3.setText(_translate("MainWindow", "Multi Tool Page Yet to be Implemented"))
        self.label_4.setText(_translate("MainWindow", "Zoek Afseuiter Page"))
        self.label_6.setText(_translate("MainWindow", "Zoek Mehingen Page"))
        self.label_7.setText(_translate("MainWindow", "Zoek SUO Page"))
        self.btn_message.setText(_translate("MainWindow", "Message"))
        self.btn_print.setText(_translate("MainWindow", "Print"))
        self.btn_logout.setText(_translate("MainWindow", "Logout"))
import resources_rc
