# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wachtwoord_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(378, 358)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("QLabel{\n"
"\n"
"    font: 87 10pt \"Roboto Black\";\n"
"\n"
"color:black;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border-radius: 5px;\n"
"    border: 1px solid gray;\n"
"    padding-left: 5px;\n"
"    selection-color: #fff;\n"
"    selection-background-color: #1159A8;\n"
"    font-family: Calibri;\n"
"color:black\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid gray;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid gray;\n"
"    background-color: #FAFAFC;\n"
"}\n"
"QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    background-color: #0061B0;\n"
"    padding: 8px;\n"
"    color:#fff;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0061B0;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: #007ACC;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 70))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.entry_wachtwoord = QtWidgets.QLineEdit(self.frame)
        self.entry_wachtwoord.setMinimumSize(QtCore.QSize(0, 30))
        self.entry_wachtwoord.setEchoMode(QtWidgets.QLineEdit.Password)
        self.entry_wachtwoord.setObjectName("entry_wachtwoord")
        self.gridLayout.addWidget(self.entry_wachtwoord, 1, 0, 1, 1)
        self.btn_inloggen = QtWidgets.QPushButton(self.frame)
        self.btn_inloggen.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_inloggen.setObjectName("btn_inloggen")
        self.gridLayout.addWidget(self.btn_inloggen, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Voer wachtwoord in:"))
        self.btn_inloggen.setText(_translate("Dialog", "Inloggen"))
